import os
import shutil

from sqlalchemy.orm import Session

from app import crud, models
from app.core.config import settings
from app.schemas.data_product import DataProductCreate
from app.tests.utils.flight import create_flight
from app.tests.utils.job import create_job
from app.tests.utils.project import create_project
from app.tests.utils.user import create_user
from app.tests.utils.user_style import create_user_style


class SampleDataProduct:
    """Sample data product for testing."""

    def __init__(
        self,
        db: Session,
        data_type: str = "dsm",
        flight: models.Flight | None = None,
        create_style: bool = False,
        project: models.Project | None = None,
        user: models.User | None = None,
        skip_job: bool = False,
    ):
        # Set up user, project, and flight
        self.data_type = data_type
        if not user:
            self.user = create_user(db)
        else:
            self.user = user

        if not project:
            self.project = create_project(db, owner_id=self.user.id)
        else:
            self.project = project

        if not flight:
            self.flight = create_flight(
                db, project_id=self.project.id, pilot_id=self.user.id
            )
        else:
            self.flight = flight

        # Copy data product to test directory
        filename, filepath = self.copy_test_data_product_to_test_directory()

        # Create data product record database
        self.obj = self.create_data_product_in_database(db, filename, filepath)

        # Create default style setting for the data product
        if create_style:
            self.user_style = create_user_style(
                db, data_product_id=self.obj.id, user_id=self.user.id
            )

        # Create job for the data product
        if not skip_job:
            self.job = create_job(db, data_product_id=self.obj.id)

    def copy_test_data_product_to_test_directory(self) -> tuple[str, str]:
        src_filepath = os.path.join(os.sep, "app", "app", "tests", "data", "test.tif")
        dest_filepath = os.path.join(
            f"{settings.TEST_UPLOAD_DIR}/projects/{self.project.id}"
            f"/flights/{self.flight.id}/myfile.tif"
        )
        if not os.path.exists(os.path.dirname(dest_filepath)):
            os.makedirs(os.path.dirname(dest_filepath))
        shutil.copyfile(src_filepath, dest_filepath)
        return os.path.basename(src_filepath), dest_filepath

    def create_data_product_in_database(
        self, db: Session, filename: str, filepath: str
    ):
        data_product_in = DataProductCreate(
            data_type=self.data_type,
            filepath=filepath,
            original_filename=filename,
            stac_properties=test_stac_props_dsm,
        )
        data_product_in_db = crud.data_product.create_with_flight(
            db, obj_in=data_product_in, flight_id=self.flight.id
        )
        return data_product_in_db


test_stac_props_dsm = {
    "raster": [
        {
            "data_type": "float32",
            "stats": {
                "minimum": 187.264,
                "maximum": 188.761,
                "mean": 187.502,
                "stddev": 0.257,
            },
            "histogram": {
                "count": 256,
                "min": 187.26136348948603,
                "max": 188.76356937184397,
                "buckets": [
                    6,
                    50,
                    120,
                    244,
                    246,
                    382,
                    286,
                    318,
                    291,
                    227,
                    220,
                    205,
                    158,
                    113,
                    205,
                    221,
                    327,
                    500,
                    915,
                    1318,
                    1755,
                    1903,
                    1973,
                    1724,
                    2011,
                    2276,
                    2282,
                    2179,
                    1901,
                    1606,
                    1499,
                    1537,
                    1619,
                    1307,
                    1132,
                    843,
                    838,
                    1032,
                    1122,
                    1078,
                    935,
                    660,
                    441,
                    412,
                    446,
                    395,
                    326,
                    289,
                    189,
                    120,
                    105,
                    118,
                    94,
                    122,
                    69,
                    61,
                    29,
                    34,
                    45,
                    34,
                    23,
                    28,
                    13,
                    4,
                    12,
                    20,
                    19,
                    11,
                    6,
                    14,
                    4,
                    6,
                    1,
                    7,
                    7,
                    10,
                    26,
                    6,
                    3,
                    1,
                    7,
                    10,
                    5,
                    8,
                    3,
                    2,
                    3,
                    1,
                    6,
                    10,
                    12,
                    9,
                    3,
                    0,
                    5,
                    7,
                    13,
                    11,
                    8,
                    5,
                    6,
                    3,
                    8,
                    4,
                    14,
                    8,
                    6,
                    0,
                    7,
                    9,
                    13,
                    23,
                    6,
                    5,
                    2,
                    10,
                    17,
                    13,
                    18,
                    13,
                    10,
                    10,
                    10,
                    26,
                    18,
                    34,
                    29,
                    27,
                    22,
                    15,
                    31,
                    26,
                    28,
                    34,
                    14,
                    7,
                    11,
                    31,
                    18,
                    20,
                    23,
                    22,
                    22,
                    10,
                    15,
                    25,
                    32,
                    52,
                    29,
                    29,
                    12,
                    22,
                    32,
                    38,
                    35,
                    39,
                    17,
                    15,
                    26,
                    37,
                    43,
                    50,
                    40,
                    25,
                    21,
                    25,
                    33,
                    44,
                    61,
                    30,
                    31,
                    19,
                    30,
                    62,
                    65,
                    64,
                    62,
                    43,
                    42,
                    47,
                    66,
                    68,
                    60,
                    48,
                    34,
                    24,
                    16,
                    30,
                    53,
                    50,
                    31,
                    13,
                    27,
                    16,
                    34,
                    22,
                    37,
                    35,
                    15,
                    17,
                    30,
                    19,
                    30,
                    39,
                    40,
                    31,
                    24,
                    15,
                    26,
                    46,
                    57,
                    38,
                    29,
                    23,
                    30,
                    25,
                    32,
                    59,
                    47,
                    22,
                    20,
                    12,
                    19,
                    38,
                    41,
                    41,
                    14,
                    23,
                    19,
                    24,
                    38,
                    28,
                    37,
                    28,
                    32,
                    17,
                    16,
                    10,
                    6,
                    21,
                    21,
                    6,
                    3,
                    6,
                    10,
                    1,
                    2,
                    3,
                    1,
                    0,
                    2,
                    0,
                    3,
                    1,
                    3,
                    4,
                ],
            },
            "nodata": None,
            "unit": "metre",
        }
    ],
    "eo": [{"name": "b1", "description": "Gray"}],
}

test_stac_props_ortho = {
    "raster": [
        {
            "data_type": "float32",
            "stats": {
                "minimum": 181.047,
                "maximum": 189.516,
                "mean": 187.329,
                "stddev": 0.675,
            },
            "histogram": {
                "count": 256,
                "min": 181.03005392036872,
                "max": 189.53307168998128,
                "buckets": [
                    1,
                    0,
                    1,
                    0,
                    1,
                    3,
                    0,
                    5,
                    3,
                    1,
                    6,
                    7,
                    5,
                    4,
                    5,
                    9,
                    15,
                    23,
                    27,
                    28,
                    37,
                    28,
                    32,
                    71,
                    95,
                    202,
                    221,
                    236,
                    302,
                    358,
                    521,
                    562,
                    610,
                    569,
                    835,
                    946,
                    1095,
                    1119,
                    1288,
                    1559,
                    1608,
                    1720,
                    1788,
                    1722,
                    1887,
                    2009,
                    2105,
                    2245,
                    2338,
                    2728,
                    2872,
                    3068,
                    2638,
                    2356,
                    2517,
                    2394,
                    2296,
                    2104,
                    2199,
                    1751,
                    1619,
                    1593,
                    1403,
                    1232,
                    1263,
                    1076,
                    961,
                    832,
                    716,
                    694,
                    667,
                    581,
                    559,
                    475,
                    524,
                    479,
                    505,
                    477,
                    437,
                    456,
                    406,
                    409,
                    347,
                    390,
                    344,
                    343,
                    352,
                    345,
                    339,
                    329,
                    319,
                    318,
                    332,
                    319,
                    335,
                    327,
                    317,
                    334,
                    327,
                    341,
                    358,
                    328,
                    304,
                    349,
                    318,
                    349,
                    364,
                    334,
                    326,
                    349,
                    339,
                    365,
                    352,
                    347,
                    380,
                    388,
                    360,
                    375,
                    397,
                    383,
                    384,
                    396,
                    409,
                    416,
                    410,
                    418,
                    422,
                    460,
                    466,
                    448,
                    474,
                    438,
                    418,
                    362,
                    261,
                    238,
                    203,
                    220,
                    215,
                    226,
                    210,
                    217,
                    222,
                    216,
                    214,
                    170,
                    161,
                    150,
                    138,
                    155,
                    171,
                    150,
                    191,
                    181,
                    183,
                    161,
                    184,
                    219,
                    176,
                    194,
                    176,
                    189,
                    201,
                    214,
                    215,
                    241,
                    238,
                    240,
                    257,
                    255,
                    275,
                    326,
                    319,
                    320,
                    378,
                    418,
                    614,
                    1124,
                    1902,
                    2578,
                    2038,
                    1385,
                    1221,
                    1970,
                    11503,
                    122970,
                    410839,
                    541915,
                    662564,
                    571742,
                    524971,
                    440539,
                    322647,
                    243975,
                    147196,
                    99499,
                    65816,
                    42914,
                    26500,
                    12875,
                    6138,
                    4356,
                    3869,
                    3818,
                    3588,
                    3477,
                    3472,
                    4203,
                    5384,
                    4380,
                    3635,
                    3744,
                    3879,
                    4181,
                    4471,
                    4878,
                    5369,
                    5645,
                    5701,
                    5624,
                    5491,
                    5540,
                    5650,
                    6055,
                    6730,
                    7582,
                    10071,
                    16308,
                    35012,
                    64503,
                    22619,
                    12050,
                    3792,
                    1093,
                    700,
                    571,
                    433,
                    280,
                    327,
                    281,
                    372,
                    582,
                    661,
                    350,
                    216,
                    174,
                    276,
                    343,
                    465,
                    584,
                    552,
                    653,
                    614,
                    468,
                    333,
                    30,
                ],
            },
            "nodata": None,
            "unit": "metre",
        }
    ],
    "eo": [
        {"name": "b1", "description": "Red"},
        {"name": "b2", "description": "Green"},
        {"name": "b3", "description": "Blue"},
        {"name": "b4", "description": "Alpha"},
    ],
}
