"""add jobs table

Revision ID: 01b7986f768b
Revises: e7b52834029e
Create Date: 2023-08-21 13:19:01.650642

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01b7986f768b'
down_revision: str | None = 'e7b52834029e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('state', postgresql.ENUM('PENDING', 'STARTED', 'COMPLETED', name='job_state'), nullable=False),
    sa.Column('status', postgresql.ENUM('WAITING', 'INPROGRESS', 'SUCCESS', 'FAILED', name='job_status'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('raw_data_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
