"""make file IDs unique for file permission records

Revision ID: 072c3b0d1571
Revises: bdbe13371b68
Create Date: 2024-01-03 15:05:58.995522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072c3b0d1571'
down_revision: str | None = 'bdbe13371b68'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_to_file_permissions', 'file_permissions', ['file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_to_file_permissions', 'file_permissions', type_='unique')
    # ### end Alembic commands ###
