"""set team_id to null on delete

Revision ID: 1c8d558efdd9
Revises: 3cdca8dad784
Create Date: 2024-03-18 17:23:24.116693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8d558efdd9'
down_revision: str | None = '3cdca8dad784'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_team_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_team_id_fkey', 'projects', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
