"""add extension tables

Revision ID: 1dd90e71b448
Revises: a7e7862fb42f
Create Date: 2024-07-15 01:29:27.344217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dd90e71b448'
down_revision: str | None = 'a7e7862fb42f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extension_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extension_id', 'user_id', name='unique_to_extension_and_user')
    )
    op.create_table('team_extensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extension_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extension_id', 'team_id', name='unique_to_extension_and_team')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_extensions')
    op.drop_table('user_extensions')
    op.drop_table('extensions')
    # ### end Alembic commands ###
