"""initial migration with uuids

Revision ID: 1ddad0ea3f41
Revises: 
Create Date: 2023-06-27 13:33:22.300504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ddad0ea3f41'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planting_date', sa.DateTime(), nullable=False),
    sa.Column('harvest_date', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('side_overlap', sa.Float(), nullable=False),
    sa.Column('forward_overlap', sa.Float(), nullable=False),
    sa.Column('sensor', postgresql.ENUM('RGB', 'Multispectral', 'LiDAR', 'Other', name='sensor_type'), nullable=False),
    sa.Column('platform', postgresql.ENUM('Phantom_4', 'M300', 'M350', 'Other', name='platform_type'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pilot_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_path', sa.String(), nullable=False),
    sa.Column('data_type', postgresql.ENUM('Ortho', 'DSM', 'PointCloud', 'Other', name='data_product_type'), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_path', sa.String(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    op.drop_table('data_products')
    op.drop_table('flights')
    op.drop_table('projects')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
