"""add fields for tracking project's active status

Revision ID: 1eb594bba349
Revises: a3be7a0a85a8
Create Date: 2023-10-17 12:51:44.650891

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1eb594bba349'
down_revision: str | None = 'a3be7a0a85a8'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.alter_column('projects', 'planting_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'planting_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('projects', 'deactivated_at')
    op.drop_column('projects', 'is_active')
    # ### end Alembic commands ###
