"""add column for demo user accounts to users table

Revision ID: 257669f1a6b6
Revises: f91e984cffea
Create Date: 2024-08-29 18:27:20.972676

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '257669f1a6b6'
down_revision: str | None = 'f91e984cffea'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
