"""add breedbase table

Revision ID: 27624a9b6278
Revises: 36e70891a65f
Create Date: 2025-05-18 22:32:52.059271

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "27624a9b6278"
down_revision: str | None = "36e70891a65f"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "breedbase_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("study_id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_breedbase_connections_study_id"),
        "breedbase_connections",
        ["study_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_breedbase_connections_study_id"),
        table_name="breedbase_connections",
    )
    op.drop_table("breedbase_connections")
    # ### end Alembic commands ###
