"""unique constraint for metadata

Revision ID: 314a512083ba
Revises: a50a73e16072
Create Date: 2024-06-03 13:48:53.654133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314a512083ba'
down_revision: str | None = 'a50a73e16072'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_metadata', 'data_product_metadata', ['data_product_id', 'vector_layer_id', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_metadata', 'data_product_metadata', type_='unique')
    # ### end Alembic commands ###
