"""add "extra" column to jobs table

Revision ID: 331ef9521713
Revises: a7e7862fb42f
Create Date: 2024-07-18 18:34:18.138369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '331ef9521713'
down_revision: str | None = 'a7e7862fb42f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'extra')
    # ### end Alembic commands ###
