"""replace band_info with stac_properties

Revision ID: 33c06c017301
Revises: ed784178e93a
Create Date: 2023-09-29 14:50:08.365439

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33c06c017301'
down_revision: str | None = 'ed784178e93a'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_products', sa.Column('stac_properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('data_products', 'band_info')
    op.create_unique_constraint('unique_to_product_and_user', 'user_styles', ['data_product_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_to_product_and_user', 'user_styles', type_='unique')
    op.add_column('data_products', sa.Column('band_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('data_products', 'stac_properties')
    # ### end Alembic commands ###
