"""add team member table

Revision ID: 377b6d9645d3
Revises: 9ab7f7a7e700
Create Date: 2023-07-06 13:01:13.787856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377b6d9645d3'
down_revision: str | None = '9ab7f7a7e700'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('team_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'team_id')
    # ### end Alembic commands ###
