"""initial migration for projects, flights, data_products, and raw_data tables

Revision ID: 38847d7554f3
Revises: a0de2818308c
Create Date: 2023-06-26 13:17:16.893266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38847d7554f3'
down_revision: str | None = 'a0de2818308c'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=False),
    sa.Column('side_overlap', sa.Float(), nullable=False),
    sa.Column('forward_overlap', sa.Float(), nullable=False),
    sa.Column('sensor', postgresql.ENUM('RGB', 'Multispectral', 'LiDAR', 'Other', name='sensor_type'), nullable=False),
    sa.Column('platform', postgresql.ENUM('Phantom_4', 'M300', 'M350', 'Other', name='platform_type'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_path', sa.String(), nullable=False),
    sa.Column('data_type', postgresql.ENUM('Ortho', 'DSM', 'PointCloud', 'Other', name='data_product_type'), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_path', sa.String(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    op.drop_table('data_products')
    op.drop_table('flights')
    # ### end Alembic commands ###
