"""drop ENUM for flight platform and data product data type

Revision ID: 3cdca8dad784
Revises: 65aabee2be5c
Create Date: 2024-02-07 19:17:00.747353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3cdca8dad784'
down_revision: str | None = '65aabee2be5c'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_products', 'data_type',
               existing_type=postgresql.ENUM('dsm', 'point_cloud', 'ortho', 'other', name='dtype'),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('flights', 'platform',
               existing_type=postgresql.ENUM('Phantom_4', 'M300', 'M350', 'Other', name='platform_type'),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('flights', 'platform',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('Phantom_4', 'M300', 'M350', 'Other', name='platform_type'),
               existing_nullable=False)
    op.alter_column('data_products', 'data_type',
               existing_type=sa.String(length=128),
               type_=postgresql.ENUM('dsm', 'point_cloud', 'ortho', 'other', name='dtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
