"""include center x,y coordinates with location

Revision ID: 404ae3bff216
Revises: 4a88cfdc3876
Create Date: 2023-08-30 18:48:51.256405

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '404ae3bff216'
down_revision: str | None = '4a88cfdc3876'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('center_x', sa.Float(), nullable=False))
    op.add_column('locations', sa.Column('center_y', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'center_y')
    op.drop_column('locations', 'center_x')
    # ### end Alembic commands ###
