"""add is_published column to projects

Revision ID: 45875ccd4674
Revises: 65ce1ac7b8a9
Create Date: 2025-04-08 20:10:46.965844

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "45875ccd4674"
down_revision: str | None = "65ce1ac7b8a9"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_published")
    # ### end Alembic commands ###
