"""add relation between job and data product

Revision ID: 4a88cfdc3876
Revises: f4dbb69e9872
Create Date: 2023-08-29 14:30:42.842960

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a88cfdc3876'
down_revision: str | None = 'f4dbb69e9872'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('data_product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'data_product', ['data_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'data_product_id')
    op.drop_table('data_product')
    # ### end Alembic commands ###
