"""add module types and project modules

Revision ID: 5c0f233cab5a
Revises: 36e70891a65f
Create Date: 2025-05-28 20:05:36.358926

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c0f233cab5a"
down_revision: str | None = "36e70891a65f"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_types",
        sa.Column(
            "module_name", sa.String(length=50), nullable=False, primary_key=True
        ),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("module_name"),
    )
    op.create_table(
        "project_modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("module_name", sa.String(length=50), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_name"],
            ["module_types.module_name"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id", "module_name", "project_id"),
        sa.UniqueConstraint("project_id", "module_name", name="uq_project_module"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_modules")
    op.drop_table("module_types")
    # ### end Alembic commands ###
