"""rename data_path column to filepath in raw_data

Revision ID: 6073062cc3fe
Revises: 83f99c7d1c34
Create Date: 2023-08-17 15:26:45.964158

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6073062cc3fe'
down_revision: str | None = '83f99c7d1c34'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('filepath', sa.String(), nullable=False))
    op.drop_column('raw_data', 'data_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('data_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('raw_data', 'filepath')
    # ### end Alembic commands ###
