"""add deactivate columns to raw data table

Revision ID: 65aabee2be5c
Revises: 833f995f8cc4
Create Date: 2024-02-02 19:56:05.888968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65aabee2be5c'
down_revision: str | None = '833f995f8cc4'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation_tokens')
    op.create_unique_constraint('unique_to_project', 'project_members', ['member_id', 'project_id'])
    op.add_column('raw_data', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('raw_data', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'deactivated_at')
    op.drop_column('raw_data', 'is_active')
    op.drop_constraint('unique_to_project', 'project_members', type_='unique')
    op.create_table('confirmation_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='confirmation_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='confirmation_tokens_pkey')
    )
    # ### end Alembic commands ###
