"""add deactivate fields to data products and flights

Revision ID: 67d6132e1edc
Revises: 1eb594bba349
Create Date: 2023-11-02 01:36:24.145842

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67d6132e1edc'
down_revision: str | None = '1eb594bba349'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('data_products', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('flights', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('flights', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'deactivated_at')
    op.drop_column('flights', 'is_active')
    op.drop_column('data_products', 'deactivated_at')
    op.drop_column('data_products', 'is_active')
    # ### end Alembic commands ###
