"""add role column for team members table

Revision ID: 696cde09bec5
Revises: a89265840b5d
Create Date: 2025-03-06 21:27:12.594861

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "696cde09bec5"
down_revision: str | None = "a89265840b5d"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type for member role
    member_role = postgresql.ENUM("OWNER", "MANAGER", "VIEWER", name="member_role")
    member_role.create(op.get_bind())
    # Add role column to team_members table
    op.add_column(
        "team_members",
        sa.Column(
            "role",
            postgresql.ENUM("OWNER", "MANAGER", "VIEWER", name="member_role"),
            server_default="VIEWER",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop role column from team_members table
    op.drop_column("team_members", "role")

    # Drop ENUM type for member role
    member_role = postgresql.ENUM("OWNER", "MANAGER", "VIEWER", name="member_role")
    member_role.drop(op.get_bind())
    # ### end Alembic commands ###
