"""add column for locking flight

Revision ID: 6e8fa1c5a361
Revises: 77410de680c6
Create Date: 2024-08-10 18:40:01.432530

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e8fa1c5a361'
down_revision: str | None = '77410de680c6'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('read_only', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'read_only')
    # ### end Alembic commands ###
