"""add treatment column to indoor project data

Revision ID: 71e3bbb3570e
Revises: e64210ef3dfe
Create Date: 2025-07-07 15:45:00.453036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '71e3bbb3570e'
down_revision: str | None = 'e64210ef3dfe'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indoor_project_data', sa.Column('treatment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indoor_project_data', 'treatment')
    # ### end Alembic commands ###
