"""add data product and raw data column for initial processing task

Revision ID: 77410de680c6
Revises: 331ef9521713
Create Date: 2024-08-07 15:47:33.035309

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77410de680c6'
down_revision: str | None = '331ef9521713'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_products', sa.Column('is_initial_processing_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('raw_data', sa.Column('is_initial_processing_completed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'is_initial_processing_completed')
    op.drop_column('data_products', 'is_initial_processing_completed')
    # ### end Alembic commands ###
