"""add band_info column to data_products table

Revision ID: 778b8124d273
Revises: 44b3aa232bea
Create Date: 2023-09-12 13:22:29.780718

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '778b8124d273'
down_revision: str | None = '44b3aa232bea'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_products', sa.Column('band_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_products', 'band_info')
    # ### end Alembic commands ###
