"""add optional description to extension

Revision ID: 839e65bfd908
Revises: af1bda1cc90b
Create Date: 2024-07-15 15:27:53.915756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '839e65bfd908'
down_revision: str | None = 'af1bda1cc90b'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extensions', 'description')
    # ### end Alembic commands ###
