"""drop 'name' field from location model

Revision ID: 83f99c7d1c34
Revises: e1550461916e
Create Date: 2023-08-16 15:19:46.639097

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83f99c7d1c34'
down_revision: str | None = 'e1550461916e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
