"""add foreign key for user to groups table

Revision ID: 87743a0a7816
Revises: 2a22701f800f
Create Date: 2023-06-20 20:35:44.467258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87743a0a7816'
down_revision: str | None = '2a22701f800f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    # ### end Alembic commands ###
