"""add project members table

Revision ID: 8a5ce008aedd
Revises: 13a5c7acda9d
Create Date: 2023-07-17 19:59:00.362089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a5ce008aedd'
down_revision: str | None = '13a5c7acda9d'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('Standard', 'Manager', name='project_role_type'), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    # ### end Alembic commands ###
