"""add file_size to data_products and raw_data

Revision ID: 8a820e756cbd
Revises: dd8e9a5e8a74
Create Date: 2026-06-24 15:49:40.864983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a820e756cbd'
down_revision: str | None = 'dd8e9a5e8a74'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_products', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('raw_data', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'file_size')
    op.drop_column('data_products', 'file_size')
    # ### end Alembic commands ###
