"""remove role from teams and projects table

Revision ID: 91995b26c3bb
Revises: ec5ccb4af0e6
Create Date: 2023-07-23 21:14:05.708617

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91995b26c3bb'
down_revision: str | None = 'ec5ccb4af0e6'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'role')
    op.drop_column('team_members', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('role', postgresql.ENUM('Standard', 'Manager', name='role_type'), autoincrement=False, nullable=False))
    op.add_column('project_members', sa.Column('role', postgresql.ENUM('Standard', 'Manager', name='project_role_type'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
