"""drop directory_structure column, add is_initial_processing_completed column

Revision ID: 9953a4575624
Revises: 71e3bbb3570e
Create Date: 2025-07-08 14:46:08.771296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9953a4575624'
down_revision: str | None = '71e3bbb3570e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indoor_project_data', sa.Column('is_initial_processing_completed', sa.Boolean(), nullable=False))
    op.drop_column('indoor_project_data', 'directory_structure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indoor_project_data', sa.Column('directory_structure', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('indoor_project_data', 'is_initial_processing_completed')
    # ### end Alembic commands ###
