"""replace datetime with date for planting and harvest date fields

Revision ID: 9ab7f7a7e700
Revises: c3feea86df78
Create Date: 2023-07-03 13:01:18.693797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab7f7a7e700'
down_revision: str | None = 'c3feea86df78'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE projects ALTER COLUMN harvest_date TYPE DATE, ALTER COLUMN planting_date TYPE DATE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE projects ALTER COLUMN harvest_date TYPE TIMESTAMP, ALTER COLUMN planting_date TYPE TIMESTAMP"
    )
    # ### end Alembic commands ###
