"""add optional name field to flights

Revision ID: a7e7862fb42f
Revises: 3bf88d6f9581
Create Date: 2024-06-25 14:32:22.808150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7e7862fb42f'
down_revision: str | None = '3bf88d6f9581'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'name')
    # ### end Alembic commands ###
