"""set unique constraint for extension name

Revision ID: af1bda1cc90b
Revises: 1dd90e71b448
Create Date: 2024-07-15 14:23:02.980662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af1bda1cc90b'
down_revision: str | None = '1dd90e71b448'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_name', 'extensions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name', 'extensions', type_='unique')
    # ### end Alembic commands ###
