"""add table for managing file permissions

Revision ID: bdbe13371b68
Revises: ef0580ce9de4
Create Date: 2024-01-03 02:37:23.127979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdbe13371b68'
down_revision: str | None = 'ef0580ce9de4'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access', postgresql.ENUM('UNRESTRICTED', 'RESTRICTED', name='access_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['data_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_permissions')
    # ### end Alembic commands ###
