"""change acquisition date from datetime to date

Revision ID: c2453e3ea2a4
Revises: efdfb4428b82
Create Date: 2023-08-13 23:06:23.750474

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2453e3ea2a4'
down_revision: str | None = 'efdfb4428b82'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'acquisition_date',
               existing_type=sa.Date(),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'harvest_date',
               existing_type=sa.DateTime(),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###
