"""add email confirmation column to users table

Revision ID: c4dda34eb7e2
Revises: 33c06c017301
Create Date: 2023-10-03 14:12:49.293632

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4dda34eb7e2'
down_revision: str | None = '33c06c017301'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_email_confirmed')
    # ### end Alembic commands ###
