"""rename data product table

Revision ID: c826c53f7353
Revises: 404ae3bff216
Create Date: 2023-09-04 19:45:47.289552

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c826c53f7353'
down_revision: str | None = '404ae3bff216'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_products', sa.Column('filepath', sa.String(), nullable=False))
    op.add_column('data_products', sa.Column('original_filename', sa.String(), nullable=False))
    op.drop_column('data_products', 'data_type')
    op.drop_column('data_products', 'data_path')
    op.create_foreign_key(None, 'jobs', 'data_products', ['data_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.add_column('data_products', sa.Column('data_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('data_products', sa.Column('data_type', postgresql.ENUM('Ortho', 'DSM', 'PointCloud', 'Other', name='data_product_type'), autoincrement=False, nullable=False))
    op.drop_column('data_products', 'original_filename')
    op.drop_column('data_products', 'filepath')
    # ### end Alembic commands ###
