"""add activity_snapshots table

Revision ID: dd8e9a5e8a74
Revises: 8d0ff98a7875
Create Date: 2026-06-24 14:05:10.048209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8e9a5e8a74'
down_revision: str | None = '8d0ff98a7875'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('active_24h', sa.Integer(), nullable=False),
    sa.Column('active_7d', sa.Integer(), nullable=False),
    sa.Column('active_30d', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_snapshots_snapshot_date'), 'activity_snapshots', ['snapshot_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_snapshots_snapshot_date'), table_name='activity_snapshots')
    op.drop_table('activity_snapshots')
    # ### end Alembic commands ###
