"""allow harvest date to be null

Revision ID: e47ef2dd67f7
Revises: 91995b26c3bb
Create Date: 2023-07-25 14:27:48.118391

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e47ef2dd67f7'
down_revision: str | None = '91995b26c3bb'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'harvest_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'harvest_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
