"""add indoor_project_data table

Revision ID: e64210ef3dfe
Revises: 3552eff5e070
Create Date: 2024-10-25 14:51:57.026207

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e64210ef3dfe'
down_revision: str | None = '3552eff5e070'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indoor_project_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('directory_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('indoor_project_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['indoor_project_id'], ['indoor_projects.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indoor_project_data')
    # ### end Alembic commands ###
