"""add role column to project members table

Revision ID: ef0580ce9de4
Revises: 18275fe01c4f
Create Date: 2023-12-12 20:29:41.002686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef0580ce9de4'
down_revision: str | None = '18275fe01c4f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('role', sa.String(length=10), nullable=False, server_default="viewer"))
    sa.UniqueConstraint('member_id', 'project_id', name='unique_to_project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'role')
    # ### end Alembic commands ###
