"""set unique constraint for team id and member id

Revision ID: efdfb4428b82
Revises: e47ef2dd67f7
Create Date: 2023-08-04 15:11:55.126258

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efdfb4428b82'
down_revision: str | None = 'e47ef2dd67f7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_to_team', 'team_members', ['member_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_to_team', 'team_members', type_='unique')
    # ### end Alembic commands ###
