"""remove team memembers if team removed

Revision ID: f49a1bc6b126
Revises: 377b6d9645d3
Create Date: 2023-07-06 15:48:01.161784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49a1bc6b126'
down_revision: str | None = '377b6d9645d3'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
