"""add relation between job and raw data

Revision ID: f4dbb69e9872
Revises: 01b7986f768b
Create Date: 2023-08-28 15:08:17.127926

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4dbb69e9872'
down_revision: str | None = '01b7986f768b'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('jobs', sa.Column('raw_data_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'raw_data', ['raw_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'raw_data_id')
    # ### end Alembic commands ###
