"""replace 'user' with 'owner' in relationship in Group model

Revision ID: f85fca666ee8
Revises: 57c24be56c4e
Create Date: 2023-06-23 14:15:14.453055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85fca666ee8'
down_revision: str | None = '57c24be56c4e'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
