"""add table for iforester records

Revision ID: f91e984cffea
Revises: a7e7862fb42f
Create Date: 2024-07-08 13:12:14.277277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f91e984cffea'
down_revision: str | None = 'a7e7862fb42f'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iforester',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dbh', sa.Float(), nullable=True),
    sa.Column('depthFile', sa.String(length=63), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('imageFile', sa.String(length=63), nullable=True),
    sa.Column('jsonPost', sa.String(length=1023), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=1023), nullable=True),
    sa.Column('phoneDirection', sa.Float(), nullable=True),
    sa.Column('phoneID', sa.String(length=63), nullable=True),
    sa.Column('species', sa.String(length=31), nullable=True),
    sa.Column('timeStamp', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('user', sa.String(length=31), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('campaigns', 'uploaded_template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('uploaded_template', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('iforester')
    # ### end Alembic commands ###
