"""add tables for data product likes and views

Revision ID: fa8f9fed28e9
Revises: 786003d898d7
Create Date: 2026-06-09 15:33:37.768452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8f9fed28e9'
down_revision: str | None = '786003d898d7'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_product_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_product_id', name='like_unique_to_data_product_and_user')
    )
    op.create_table('data_product_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('data_product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('user_id IS NOT NULL OR session_id IS NOT NULL', name='dp_view_requires_viewer_identity'),
    sa.ForeignKeyConstraint(['data_product_id'], ['data_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dp_views_data_product_id', 'data_product_views', ['data_product_id'], unique=False)
    op.create_index('ix_dp_views_dp_id_session_id_viewed_at', 'data_product_views', ['data_product_id', 'session_id', 'viewed_at'], unique=False, postgresql_where=sa.text('session_id IS NOT NULL'))
    op.create_index('ix_dp_views_dp_id_user_id_viewed_at', 'data_product_views', ['data_product_id', 'user_id', 'viewed_at'], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dp_views_dp_id_user_id_viewed_at', table_name='data_product_views', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_dp_views_dp_id_session_id_viewed_at', table_name='data_product_views', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_index('ix_dp_views_data_product_id', table_name='data_product_views')
    op.drop_table('data_product_views')
    op.drop_table('data_product_likes')
    # ### end Alembic commands ###
